FROM centos:7
MAINTAINER crunchy

RUN rpm -Uvh http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-1.noarch.rpm
RUN yum install -y procps-ng postgresql94 postgresql94-server unzip openssh-clients hostname bind-utils && yum clean all -y

RUN mkdir -p /opt/cpm/bin
ADD bin/backup/ /opt/cpm/bin
RUN chown -R postgres:postgres /opt/cpm
ENV PGROOT /usr/pgsql-9.4

VOLUME ["/pgdata"]
RUN chown -R postgres:postgres /pgdata

USER postgres

CMD ["/opt/cpm/bin/start-backupjob.sh"]
