== Crunchy PostgreSQL Containers

This project includes a set of Dockerfiles that lets you build
the Crunchy Certified PostgreSQL 9.5 Docker images.  

The image by default is built on a RHEL 7.2 64 bit base, but 
can also be built on a centos 7 64 bit base.  NOTE:  to build the RHEL 7 
version of this container, you need to build the Docker
container on a licensed RHEL 7 host!

The containers will execute in a couple of environments:

 * Standalone - run the containers on a simple Docker environment
 * Openshift - run the containers within an Openshift environment


=== Build Prerequisites

1) Installing / configuring Docker

On an EL7 system, docker can be installed with the following commands:
 * sudo yum -y install docker
 * sudo groupadd docker
 * sudo gpasswd -a ${USER} docker
 * newgrp docker
 * sudo systemctl start docker

2) Installing / configuring Go

"Go" can be installed with the following command:
 * sudo yum -y install golang

To build the containers, add the following lines to your
environment, adjusting the GOPATH as fits your actual path:

....
export GOPATH=$HOME/openshift-dedicated-container
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
....

3) Setting up config files for compilation

In order to compile the openshift-dedicated-container code, two files must be placed in the conf directory:

 * crunchypg95.repo or crunchypg93.repo
 * CRUNCHY-GPG-KEY.public

Both of these files can be obtained with the following procedure:

 * Request an account on access.crunchydata.com
 * Go to https://access.crunchydata.com/
 * In the upper-right, click "Customer Log In"
 * Enter your provided username and password
 * Click "submit"
 * Read the terms of use and click "I agree"
 * Change your password (first login) by Clicking on "Profile" in the upper right; enter your old password, a new password, and click "Change password"
 * Click on "Downloads" in the upper right corner
 * The "Download GPG Key" button will automatically download the CRUNCHY-GPG-KEY.public file
 * The "Download repo file (RHEL)" button will automatically download a personalized (to your user) crunchypg95.repo file

To build the documentation, you need some things installed:
....
yum -y install asciidoc
wget http://laurent-laville.org/asciidoc/bootstrap/bootstrap-4.5.0.zip
asciidoc --backend install ./bootstrap-4.5.0.zip
cd $HOME
mv .asciidoc/backends/asciidoc/asciidoc-bootstrap-backend-4.5.0/* .asciidoc/backends/bootstrap
mkdir -p .asciidoc/backends/bootstrap/js
cp ./openshift-dedicated-container/docs/bootstrap.js .asciidoc/backends/bootstrap/js/
sudo yum -y install ruby
gem install --pre asciidoctor-pdf
....


=== Installation

Build targets include two environment variables that determine
the Docker base image to be used and the version of Postgresql to
use.

Modify the following Makefile env variables for your desired
target, currently rhel7 and centos7 are supported OS base images
and 9.3 and 9.5 are supported versions of Postgresql:

....
OSFLAVOR=rhel7
PGVERSION=9.3
....

Docker image builds are performed by issuing the make command:
....
make
....

This will build the following Docker images:

 * crunchy-pg
 * crunchy-backup
 * crunchy-pgpool
 * crunchy-pgbadger

For most of the examples, I use the psql command as a postgres client.  To install PostgreSQL locally, run the following:

....
sudo rpm -Uvh http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-redhat94-9.4-1.noarch.rpm
sudo yum -y install postgresql94-server postgresql94
....

The installation of postgres locally is also required to create a postgres user and group which are
used by the examples to set the correct file permissions on local files used by the containers.

=== crunchy-pg Configuration Options

You can adjust the following Postgres configuration parameters
by setting environment variables:
....
MAX_CONNECTIONS - defaults to 100
SHARED_BUFFERS - defaults to 128MB
TEMP_BUFFERS - defaults to 8MB
WORK_MEM - defaults to 4MB
MAX_WAL_SENDERS - defaults to 6
....

You have the ability to override the pg_hba.conf and postgresql.conf
files used by the container.  To enable this, you create a 
directory to hold your own copy of these configuration files.

Then you mount that directory into the container using the /pgconf
volume mount as follows:

....
-v $YOURDIRECTORY:/pgconf
....

Inside YOURDIRECTORY would be your pg_hba.conf and postgresql.conf
files.  These files are not manipulated or changed by the container
start scripts.

Various examples are provided in the /examples directory.

